version: "3"

services:
  vanetlab-web:
    build: ../vanetlab-web
    labels:
      - "traefik.http.routers.vanetlab-web.rule=Host(`team08-22.studenti.fiit.stuba.sk`)"
  vanetlab-be: 
    build: ../vanetlab-be
    environment:
      - VANETLAB_BE_PORT:"9000"
      - VANETLAB_BE_HOST:"0.0.0.0"
    ports:
      - "9000:9000"
    labels:
      - "traefik.http.routers.vanetlab-be.rule=Host(`vanetlab.ml`)&&PathPrefix(`/api`)"
  vanetlab-fe:
    build: .
    environment:
            - VITE_BE_API_URL:"http://127.0.0.1:9000/api"
    labels:
      - "traefik.http.routers.vanetlab-fe.rule=Host(`vanetlab.ml`)"
  traefik:
    image: traefik:v2.9
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
